dist: xenial
sudo: required
language: rust
services:
  - xvfb
rust:
  - nightly
  - beta
  - 1.40.0 # stable

env:
  - GTK=3.14
  - GTK=3.24

addons:
  apt:
    packages:
      - libcurl4-openssl-dev
      - libelf-dev
      - libdw-dev
      - binutils-dev
      - libgtk-3-dev
      - libmount-dev
      - libsoup2.4-dev
      - libxtst-dev
      - at-spi2-core
      - openbox
      - libxdo-dev

before_script:
  - openbox & # needs a window manager for the tests (to get focus to work)

script:
  - rustc --version
  - if [ "$TRAVIS_RUST_VERSION" == "nightly" ]; then
    rustup component add clippy;
    cargo clippy --release;
    fi
  - cargo build
  - cargo test -- --test-threads 1
