sudo: required
language: rust
rust:
  - nightly
  - beta
  - stable

env:
  - GTK=3.4
  - GTK=3.18

addons:
  apt:
    packages:
      - libcurl4-openssl-dev
      - libelf-dev
      - libdw-dev
      - binutils-dev
      - libgtk-3-dev
      - libsoup2.4-dev
      - libxtst-dev
      - at-spi2-core
      - openbox

before_script:
  - "export DISPLAY=:99.0"
  - "sh -e /etc/init.d/xvfb start"
  - sleep 3 # give xvfb some time to start
  - openbox & # needs a window manager for the tests (to get focus to work)

script:
  - rustc --version
  - cargo install clippy || touch clippy_failed
  - if [ ! -f clippy_failed ]; then cargo clippy; fi
  - cargo build
  - cargo test -- --test-threads 1
