on: [push]

name: Linux CI

jobs:
  check:
    name: Compile and Test
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Install gtk3 and dependencies.
        run: |
          sudo apt update
          sudo apt install \
            libgtk-3-dev \
            libxdo-dev

      - name: Install Rust
        uses: actions-rs/toolchain@v1
        with:
          profile: minimal
          toolchain: stable
          override: true
      
      - name: Check Code
        uses: actions-rs/cargo@v1
        with:
          command: check

      - name: Install Clippy
        run: rustup component add clippy

      - name: Run Clippy
        run: cargo clippy --all-targets -- -D warnings -A unknown-lints
          
      - name: Run headless test
        uses: GabrielBB/xvfb-action@v1
        with:
          run: cargo test -- --test-threads=1
