on: [push]

name: Linux CI

jobs:
  check:
    name: Compile and Test
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Install gtk3 and dependencies.
        run: sudo apt-get update && sudo apt install menu libcurl4-openssl-dev libelf-dev libdw-dev binutils-dev libgtk-3-dev libmount-dev libsoup2.4-dev libxtst-dev at-spi2-core openbox

      - name: Install Rust
        uses: actions-rs/toolchain@v1
        with:
          profile: minimal
          toolchain: stable
          override: true
      
      - name: Check Code
        uses: actions-rs/cargo@v1
        with:
          command: check
          
      - name: Setup OpenBox environment.
        run: |
              Xvfb -ac :99 -screen 0 1280x1024x16 > /dev/null 2>&1 &
              export DISPLAY=:99
              openbox &
          
      - name: Run Tests
        uses: actions-rs/cargo@v1
        with:
          command: test
          args: -- --test-threads=1
